version: "3.9"

services:
  auth:
    build: .
    container_name: auth-service
    ports:
      - "8080:1489"
    environment:
      RUN_ADDRESS: ":1489"
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=auth_db sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 3s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC (Jaeger принимает)
      - "4318:4318"     # OTLP HTTP (на всякий)
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
      image: otel/opentelemetry-collector-contrib:0.96.0
      command: [ "--config=/etc/otelcol/config.yaml" ]
      volumes:
        - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
      ports:
        - "4319:4317"  # (не обязательно) если хочешь выделить collector наружу
        - "4320:4318"
      depends_on:
        - jaeger

volumes:
  pgdata: